_wandb:
    value:
        cli_version: 0.19.2
        m: []
        python_version: 3.8.16
        t:
            "1":
                - 1
                - 5
                - 11
                - 33
                - 49
                - 51
                - 53
                - 55
                - 71
            "2":
                - 1
                - 5
                - 11
                - 33
                - 49
                - 51
                - 53
                - 55
                - 71
            "3":
                - 23
                - 55
            "4": 3.8.16
            "5": 0.19.2
            "6": 4.46.3
            "8":
                - 5
            "12": 0.19.2
            "13": linux-x86_64
